TRAIN_FILE = "train.txt"
VAL_FILE = "validation.txt"
TAG_FILE = "tag.txt"

LEARNING_RATE = 3e-4
BATCH_SIZE = 32
EPOCHS = 40
WEIGHT_DECAY = 1e-4

EARLY_STOP_PATIENCE = 6
EARLY_STOP_MIN_DELTA = 0.0

D_MODEL = 256
NHEAD = 8
NUM_ENCODER_LAYERS = 2
DIM_FEEDFORWARD = 512
DROPOUT = 0.15

MAX_SEQ_LEN = 256
UNK_MIN_FREQ = 1

TRAIN_RANDOM_SEED = 42

PAD_TOKEN = "<pad>"
UNK_TOKEN = "<unk>"

MAX_GRAD_NORM = 1.0
